/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2018-03-27 04:43:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.system.activity;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;

public final class redEnvelopeManager_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/jsp/system/activity/../../common/include/util.jsp", Long.valueOf(1521710765619L));
    _jspx_dependants.put("/WEB-INF/jsp/common/include/Taglibs.jsp", Long.valueOf(1521710765618L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    response.setHeader("Content-Type","text/html; charset=utf-8");
    request.setCharacterEncoding("utf-8");
    pageContext.setAttribute("pageEncoding","utf-8");
    
	String apppath = request.getContextPath();
	request.setAttribute("apppath", apppath);
	
	Date d = new Date();
	String tabid = "tabid"+d.getTime();
	request.setAttribute("tabid", tabid);

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/validatebox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/common/common.js\"></script>");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<table id=\"redEnvelopeList\" title=\"红包管理\" class=\"easyui-datagrid\"\r\n");
      out.write("\t\tstyle=\"height:99%;width:99.9%\"\r\n");
      out.write("\t\tdata-options=\"singleSelect:true,\r\n");
      out.write("\t    fitColumns:true, url: '../activity/redEnvelopeManager.do',\r\n");
      out.write("\t    method:'post',rownumbers:true, \r\n");
      out.write("\t    pagination:true,toolbar:'#redEnvelopeTools'\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'id'\" hidden=\"hidden\">红包ID</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'code'\" width=\"10%\">红包编号</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'name'\" width=\"10%\">红包名称</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'amount'\" styler=\"styleColor\" width=\"6%\" formatter=\"formatAmount\">红包金额</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'enableAmount'\" styler=\"styleColor\" width=\"8%\" formatter=\"formatAmount\">启用金额</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'grantQty'\" width=\"6%\">发放数量</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'usedQty'\" width=\"6%\">已使用数量</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'surplusQty'\" width=\"6%\">剩余数量</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'deadline'\" width=\"6%\">有效期限(天)</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'productDeadline'\" width=\"6%\">产品期限(天)</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'applicableScenarios'\" width=\"6%\" formatter=\"formatScenarios\">适用场景</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'status'\" formatter=\"formatStatus\" width=\"6%\">状态</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'addName'\" width=\"6%\">添加人</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'addTime'\" formatter=\"formatDateBoxFull\" width=\"10%\">添加时间</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'updateName'\" width=\"6%\">修改人</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'updateTime'\" formatter=\"formatDateBoxFull\" width=\"10%\">修改时间</th>\r\n");
      out.write("\t\t\t\t<th data-options=\"field:'_operate',width:100,align:'center',formatter:formatOper\">基本操作</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div id=\"redEnvelopeTools\" style=\"padding:5px;height:750\">\r\n");
      out.write("\t\t<form id=\"redEnvelopeForm\">\r\n");
      out.write("\t\t\t<input id=\"searchType\" name=\"type\" value=\"1\" hidden=\"hidden\" /> \r\n");
      out.write("\t\t\t红包金额：<input class=\"easyui-numberbox\" id=\"searchRedEnvelopeAmount\" name=\"amount\" size=\"15\" style=\"width:150px\" />\r\n");
      out.write("\t\t\t红包名称：<input class=\"easyui-textbox\" id=\"searchRedEnvelopeName\" name=\"name\" size=\"15\" style=\"width:150px\" />\r\n");
      out.write("\t\t\t状态：<select\r\n");
      out.write("\t\t\t\tid=\"searchActivityStatus\" name=\"status\" style=\"width:100px;\"\r\n");
      out.write("\t\t\t\tclass=\"easyui-combobox\">\r\n");
      out.write("\t\t\t\t<option value=''>全部</option>\r\n");
      out.write("\t\t\t\t<option value='0'>生效中</option>\r\n");
      out.write("\t\t\t\t<option value='1'>使用中</option>\r\n");
      out.write("\t\t\t\t<option value='2'>已失效</option>\r\n");
      out.write("\t\t\t</select> \r\n");
      out.write("\t\t\t<a id=\"searchActivityBtn\" href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-search\">查询</a> \r\n");
      out.write("\t\t\t<a id=\"resetActivityBtn\" href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-reload\">重置</a> \r\n");
      out.write("\t\t\t<a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-add\" onclick=\"addredEnvelopeDialog()\">新增</a>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 新增红包活动 -->\r\n");
      out.write("\t<div id=\"addRedEnvelopeDialog\" class=\"easyui-dialog\" title=\"新增红包\"\r\n");
      out.write("\t\tdata-options=\"iconCls:'icon-edit',closed:true,modal:true,minimizable:false,resizable:true,maximizable:false,buttons:'#addRedEnvelopeBtn'\"\r\n");
      out.write("\t\tstyle=\"width:550px;height:300px;padding:20px;\">\r\n");
      out.write("\t\t<form id=\"addRedEnvelopeForm\">\r\n");
      out.write("\t\t\t<table align=\"center\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"type\" hidden=\"hidden\" value=\"1\" readonly=\"readonly\"/>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td  style=\"width:100px\">红包编号:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"code\" class=\"easyui-textbox\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"width:100px\">红包名称:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"name\" class=\"easyui-textbox\" data-options=\"required:true\" /></td>\r\n");
      out.write("\t\t\t\t\t<td style=\"width:100px\">红包金额:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"amount\" class=\"easyui-numberbox\" data-options=\"precision:2,groupSeparator:',',required:true\" />\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>启用金额:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"enableAmount\" class=\"easyui-numberbox\" data-options=\"groupSeparator:',',required:true\" /></td>\r\n");
      out.write("\t\t\t\t\t<td>发放数量:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"grantQty\" class=\"easyui-numberbox\" data-options=\"required:true\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>适用场景：</td>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"telephoneSales\" name=\"applicableScenarios\" type=\"radio\" value=\"0\" />电销使用 \r\n");
      out.write("\t\t\t\t\t\t<input id=\"activity\" name=\"applicableScenarios\" type=\"radio\" value=\"1\" />活动使用\r\n");
      out.write("\t\t\t\t\t\t<input id=\"operational\" name=\"applicableScenarios\" type=\"radio\" value=\"2\" />运营使用\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr> \r\n");
      out.write("\t\t\t\t<!-- <tr>\r\n");
      out.write("\t\t\t\t\t<td>适用产品：</td>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"optimization\" name=\"applicableProducts\" type=\"checkbox\" value=\"2\" />票据优选\r\n");
      out.write("\t\t\t\t\t\t<input id=\"security\" name=\"applicableProducts\" type=\"checkbox\" value=\"3\" />票据安选\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr> -->\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>适用用户：</td>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"all\" name=\"applicableUser\" type=\"radio\" value=\"0\" />所有用户 \r\n");
      out.write("\t\t\t\t\t\t<input id=\"general\" name=applicableUser type=\"radio\" value=\"1\" />普通用户 \r\n");
      out.write("\t\t\t\t\t\t<input id=\"woolParty\" name=\"applicableUser\" type=\"radio\" value=\"2\" />羊毛党\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>有效期限:</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"width:120px\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"deadline\" style=\"width:110px\" name=\"deadline\" type=\"text\" class=\"easyui-numberbox\" data-options=\"required:true\" > (天)\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>产品期限≥:</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"width:120px\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"productDeadline\" style=\"width:110px\" name=\"productDeadline\" type=\"text\" class=\"easyui-numberbox\" data-options=\"required:true\" > (天)\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<div id=\"#addRedEnvelopeBtn\" align=\"center\">\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" iconCls=\"icon-add\" onclick=\"addRedEnvelope()\">添加</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"updateActivityWindow\" class=\"easyui-window\"\r\n");
      out.write("\t\tdata-options=\"iconCls:'icon-edit',closed:true,modal:true,minimizable:false,resizable:false,maximizable:false\"\r\n");
      out.write("\t\tstyle=\"width:550px;height:380px;padding:10px;\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t//重置按钮\r\n");
      out.write("\t$('#resetActivityBtn').click(function(){\r\n");
      out.write("\t\t$(\"#redEnvelopeForm\").form(\"reset\");\r\n");
      out.write("\t\t$(\"#redEnvelopeList\").datagrid(\"load\", {});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//查询按钮\r\n");
      out.write("\t$('#searchActivityBtn').click(function(){\r\n");
      out.write(" \t\t$('#redEnvelopeList').datagrid({\r\n");
      out.write("\t\t\tqueryParams: {\r\n");
      out.write("\t\t\t\tamount:$('#searchRedEnvelopeAmount').val(),\r\n");
      out.write("\t\t\t\tname:$('#searchRedEnvelopeName').val(),\r\n");
      out.write("\t\t\t\tstatus:$('#searchActivityStatus').combobox(\"getValue\"),\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}); \r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//跳转到添加页面\r\n");
      out.write("\tfunction addredEnvelopeDialog(){  \r\n");
      out.write("\t\t$(\"#addRedEnvelopeForm\").form(\"reset\");\r\n");
      out.write("\t\t$(\"#addRedEnvelopeDialog\").dialog(\"open\");\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction addRedEnvelope(){\r\n");
      out.write("\t\tvar validate = $(\"#addRedEnvelopeForm\").form(\"validate\");\r\n");
      out.write("\t\tif(!validate){\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(!validata(\"applicableScenarios\")){\r\n");
      out.write("\t\t\t$.messager.alert(\"提示信息\",\"选择适用场景\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(!validata(\"applicableUser\")){\r\n");
      out.write("\t\t\t$.messager.alert(\"提示信息\",\"选择适用用户群\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("         \turl: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/activity/addActivityParameter.do\",\r\n");
      out.write("           \ttype: 'POST',\r\n");
      out.write("           \tdata:$(\"#addRedEnvelopeForm\").serialize(),  \r\n");
      out.write("           \tsuccess:function(result){\r\n");
      out.write("\t\t\t\tif(result.success){\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"提示信息\",result.msg);\r\n");
      out.write("\t\t\t\t\t$(\"#redEnvelopeList\").datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t\t$(\"#addRedEnvelopeDialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"提示信息\",result.errorMsg);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("       \t});\r\n");
      out.write("        return false; // 阻止表单自动提交事件\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction validata(str){\r\n");
      out.write("\t\tvar checkboxes = document.getElementsByName(str);\r\n");
      out.write("\t\tfor(var i=0;i<checkboxes.length;i++){\r\n");
      out.write("\t\t\tif(checkboxes[i].checked){\r\n");
      out.write("     \t\t\treturn true;\r\n");
      out.write("     \t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t//跳转到红包活动修改页面\r\n");
      out.write("\tfunction updateActivityWindow(index){\r\n");
      out.write("\t\t$('#redEnvelopeList').datagrid('selectRow',index);// 关键在这里 \r\n");
      out.write("\t    var row = $('#redEnvelopeList').datagrid('getSelected'); \r\n");
      out.write("\t\t$(\"#updateActivityWindow\").window({\r\n");
      out.write("\t\t\ttitle:\"修改红包\",\r\n");
      out.write("\t\t\thref:\"../activity/toActivityModify.do?id=\"+row.id\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#updateActivityWindow\").window(\"open\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//添加基本操作链接\r\n");
      out.write("\tfunction formatOper(val,row,index){  \r\n");
      out.write("\t\tif(2 != row.status){\r\n");
      out.write("\t\t\treturn '<a href=\"#\" class=\"btn l-btn l-btn-small\" onclick=\"updateActivityWindow('+index+')\">修改信息</a>';  \r\n");
      out.write("\t\t}\r\n");
      out.write("    \t\r\n");
      out.write("\t} \r\n");
      out.write("\t\r\n");
      out.write("\t//修改显示状态信息\r\n");
      out.write("\tfunction formatStatus(value,row,index){\r\n");
      out.write("\t\tif(row.status==\"0\"){\r\n");
      out.write("\t\t\treturn '生效中';\r\n");
      out.write("\t\t}else if(row.status==\"1\"){\r\n");
      out.write("\t\t\treturn '使用中';\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\treturn '已失效';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction formatAmount(value,rec,index){\r\n");
      out.write("\t\tif(value==0||value==null)\r\n");
      out.write("\t\t\treturn '0.00';\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\treturn (value.toFixed(2) + '').replace(/\\d{1,3}(?=(\\d{3})+(\\.\\d*)?$)/g, '$&,');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction formatScenarios(value,row,index){\r\n");
      out.write("\t\tif(value==0){\r\n");
      out.write("\t\t\treturn '电销使用';\r\n");
      out.write("\t\t}else if(value==1){\r\n");
      out.write("\t\t\treturn '活动使用';\r\n");
      out.write("\t\t}else if(value==2){\r\n");
      out.write("\t\t\treturn '运营使用';\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\treturn '';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
