/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2018-04-09 07:11:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.system.orderManager;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;

public final class regMemberInfoList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/jsp/system/orderManager/../../common/include/util.jsp", Long.valueOf(1523153962925L));
    _jspx_dependants.put("/WEB-INF/jsp/common/include/Taglibs.jsp", Long.valueOf(1523153962924L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    response.setHeader("Content-Type","text/html; charset=utf-8");
    request.setCharacterEncoding("utf-8");
    pageContext.setAttribute("pageEncoding","utf-8");
    
	String apppath = request.getContextPath();
	request.setAttribute("apppath", apppath);
	
	Date d = new Date();
	String tabid = "tabid"+d.getTime();
	request.setAttribute("tabid", tabid);

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/validatebox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/common/common.js\"></script>");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<table id=\"regMemberInfoList\" title=\"用户列表\" \r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\t   style=\"height:99%;\" remoteSort=\"true\"\r\n");
      out.write("\tdata-options=\"singleSelect:true,\r\n");
      out.write("\t    fitColumns:true, \r\n");
      out.write("\t    method:'post',rownumbers:true, \r\n");
      out.write("\t    pagination:true,toolbar:'#drProductInvestTools'\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t    <tr>\r\n");
      out.write("\t        <th data-options=\"field:'realname'\" width=\"50px\">用户姓名</th>\r\n");
      out.write("\t        <th data-options=\"field:'mobilePhone'\" width=\"80px\" >手机号码</th>\r\n");
      out.write("\t        <th data-options=\"field:'regdate'\" width=\"120px\">注册日期</th>\r\n");
      out.write("\t        <th data-options=\"field:'bankName'\" width=\"100px\">绑卡银行</th>\r\n");
      out.write("\t        <th data-options=\"field:'channelName'\" width=\"80px\">注册渠道</th>\r\n");
      out.write("\t        <th data-options=\"field:'balance'\" sortable=\"true\" styler=\"styleColor\" width=\"100px\">账户余额<span id=\"balanceSort\" style=\"color: blue;\">↓↑</span></th>\r\n");
      out.write("\t        <th data-options=\"field:'freeze'\" sortable=\"true\" styler=\"styleColor\" width=\"100px\">冻结金额<span id=\"freezeSort\" style=\"color: blue;\">↓↑</span></th>\r\n");
      out.write("\t        <th data-options=\"field:'wprincipal'\" sortable=\"true\" styler=\"styleColor\" width=\"100px\">待收本金<span id=\"wprincipalSort\" style=\"color: blue;\">↓↑</span></th>\r\n");
      out.write("\t        <th data-options=\"field:'totalAmount'\" sortable=\"true\" styler=\"styleColor\" width=\"100px\">资产总额<span id=\"totalAmountSort\" style=\"color: blue;\">↓↑</span></th>\r\n");
      out.write("\t        <th data-options=\"field:'investAmount'\" sortable=\"true\" styler=\"styleColor\" width=\"100px\">累计投资额<span id=\"investAmountSort\" style=\"color: blue;\">↓↑</span></th>\r\n");
      out.write("\t        <th data-options=\"field:'keyWord'\" width=\"75px\">注册关键字</th>\r\n");
      out.write("\t        <th data-options=\"field:'regfrom'\" width=\"75px\">注册终端</th>\r\n");
      out.write("\t        <th data-options=\"field:'isCrush'\" width=\"75px\">是否充值</th>\r\n");
      out.write("\t        <th data-options=\"field:'isInvest'\" width=\"75px\">是否投资</th>\r\n");
      out.write("\t\t\t<th data-options=\"field:'level'\" width=\"auto\" formatter=\"formaterVIP\">用户等级</th>\r\n");
      out.write("\t\t\t<th data-options=\"field:'recomRealName'\" width=\"85px\">推荐人姓名</th>\r\n");
      out.write("\t\t\t<th data-options=\"field:'recomMobilePhone'\" width=\"100px\">推荐人号码</th>\r\n");
      out.write("\t    </tr>\r\n");
      out.write("\t    </thead>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div id=\"drProductInvestTools\" style=\"padding:5px;height:750\">\r\n");
      out.write("\t  \t<form id=\"drProductInvestForm\">\r\n");
      out.write("\t  \t\t用户手机:<input id=\"searchRegMobilephone\" name=\"mobilephone\" class=\"easyui-textbox\"  size=\"30\" style=\"width:100px\"/>\r\n");
      out.write("\t  \t\t用户姓名:<input id=\"searchRegRealname\" name=\"realname\" class=\"easyui-textbox\"  size=\"30\" style=\"width:100px\"/>\r\n");
      out.write("\t  \t\t注册日期:<input id=\"searchRegStartDate\" name=\"startDate\" class=\"easyui-datebox\" style=\"width:100px\" />到\r\n");
      out.write("\t  \t\t\t\t<input id=\"searchRegEndDate\" name=\"endDate\" class=\"easyui-datebox\" style=\"width:100px\"/>\r\n");
      out.write("\t  \t\t渠道名称:<select class=\"easyui-combogrid\" id=\"cid\" name=\"cid\" style=\"width:240px;padding-bottom: 3px;\" data-options=\"\r\n");
      out.write("\t\t\t\t\t\t\tpanelWidth: 240,\r\n");
      out.write("\t\t\t\t\t\t\tmultiple: true,\r\n");
      out.write("\t\t\t\t\t\t\tmultiline:true,\r\n");
      out.write("\t\t\t\t\t\t\teditable:false,\r\n");
      out.write("\t\t\t\t\t\t\tidField: 'id',\r\n");
      out.write("\t\t\t\t\t\t\ttextField: 'name',\r\n");
      out.write("\t\t\t\t\t\t\turl: '../channel/drAllChannelInfoList.do',\r\n");
      out.write("\t\t\t\t\t\t\tmethod: 'get',\r\n");
      out.write("\t\t\t\t\t\t\tcolumns: [[\r\n");
      out.write("\t\t\t\t\t\t\t\t{field:'id',checkbox:true},\r\n");
      out.write("\t\t\t\t\t\t\t\t{field:'code',title:'渠道号',width:80},\r\n");
      out.write("\t\t\t\t\t\t\t\t{field:'name',title:'渠道名称',width:80},\r\n");
      out.write("\t\t\t\t\t\t\t]],\r\n");
      out.write("\t\t\t\t\t\t\tfitColumns: true\r\n");
      out.write("\t\t\t\t\t\t\">\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t关键字:<input id=\"searchRegKeyWord\" name=\"keyWord\" class=\"easyui-textbox\" size=\"50\" style=\"width:100px\"/>\r\n");
      out.write("\t\t\t是否投资:<select id=\"isInvest\" class=\"easyui-combobox\" name=\"isInvest\" style=\"width:200px;\">   \r\n");
      out.write("\t\t\t\t\t    <option value=\"\">全部</option>   \r\n");
      out.write("\t\t\t\t\t    <option value=\"1\">是</option>   \r\n");
      out.write("\t\t\t\t\t    <option value=\"0\">否</option>   \r\n");
      out.write("\t\t\t\t\t</select> \r\n");
      out.write("\t\t\t是否充值:<select id=\"isCrush\" class=\"easyui-combobox\" name=\"isInvest\" style=\"width:200px;\">   \r\n");
      out.write("\t\t\t\t\t    <option value=\"\">全部</option>   \r\n");
      out.write("\t\t\t\t\t    <option value=\"1\">是</option>   \r\n");
      out.write("\t\t\t\t\t    <option value=\"0\">否</option>   \r\n");
      out.write("\t\t\t\t\t</select> \r\n");
      out.write("\t\t\t用户等级: <select  id=\"searchMemberCarryLevel\" name=\"level\" style=\"width:100px;\" class=\"easyui-combobox\">\r\n");
      out.write("\t\t\t\t\t \t<option value=''>全部</option>\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("</select><br/>\r\n");
      out.write("\t                      注册终端:<select class=\"easyui-combogrid\" id=\"regfrom\" name=\"regfrom\" style=\"width:240px;padding-bottom: 3px;\" data-options=\"\r\n");
      out.write("\t\t\t\t\t\t\tpanelWidth: 240,\r\n");
      out.write("\t\t\t\t\t\t\tmultiple: true,\r\n");
      out.write("\t\t\t\t\t\t\tmultiline:true,\r\n");
      out.write("\t\t\t\t\t\t\teditable:false,\r\n");
      out.write("\t\t\t\t\t\t\tidField: 'id',\r\n");
      out.write("\t\t\t\t\t\t\ttextField: 'name',\r\n");
      out.write("\t\t\t\t\t\t\turl: '../terminal/drTerminalList.do',\r\n");
      out.write("\t\t\t\t\t\t\tmethod: 'get',\r\n");
      out.write("\t\t\t\t\t\t\tcolumns: [[\r\n");
      out.write("\t\t\t\t\t\t\t\t{field:'id',checkbox:true},\r\n");
      out.write("\t\t\t\t\t\t\t\t{field:'name',title:'终端名称',width:80},\r\n");
      out.write("\t\t\t\t\t\t\t]],\r\n");
      out.write("\t\t\t\t\t\t\tfitColumns: true\r\n");
      out.write("\t\t\t\t\t\t\">\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t资产总额:<input id=\"searchTotalAmountS\" name=\"minTotalAmount\" class=\"easyui-textbox\" value=\"\" size=\"30\" style=\"width:100px\"/>&nbsp;至\r\n");
      out.write("\t\t\t\t\t<input id=\"searchTotalAmountE\" name=\"maxTotalAmount\" class=\"easyui-textbox\" value=\"\" size=\"30\" style=\"width:100px\"/>\t\t\r\n");
      out.write("\t\t\t累计投资额:<input id=\"searchInvestAmountS\" name=\"minInvestAmount\" class=\"easyui-textbox\" value=\"\" size=\"30\" style=\"width:100px\"/>&nbsp;至\r\n");
      out.write("\t\t\t\t\t<input id=\"searchInvestAmountE\" name=\"maxInvestAmount\" class=\"easyui-textbox\" value=\"\" size=\"30\" style=\"width:100px\"/>\t\t\t\r\n");
      out.write("\t    \t<a id=\"search\" href=\"javascript:void(0)\" class=\"easyui-linkbutton\" iconCls=\"icon-search\">查询</a>\r\n");
      out.write("\t    \t<a id=\"export\" href=\"javascript:exportRegMemberInfo();\" class=\"easyui-linkbutton\" iconCls=\"icon-redo\">导出</a>\r\n");
      out.write("\t    </form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t//查询按钮\r\n");
      out.write("\t$('#search').click(function(sort,order){\r\n");
      out.write("\t\tvar cids = $('#cid').combogrid('getValues')+\"\";\r\n");
      out.write("\t\tvar regfrom = $('#regfrom').combogrid('getValues')+\"\";\r\n");
      out.write(" \t\t$('#regMemberInfoList').datagrid({\r\n");
      out.write(" \t\t\turl: '../regMemberInfo/regMemberInfoList.do',\r\n");
      out.write("\t\t\tqueryParams: {\r\n");
      out.write("// \t\t\t\tsort:sort,\r\n");
      out.write("\t\t\t\tminInvestAmount:$('#searchInvestAmountS').val(),\r\n");
      out.write("\t\t\t\tmaxInvestAmount:$('#searchInvestAmountE').val(),\r\n");
      out.write("\t\t\t\tminTotalAmount:$('#searchTotalAmountS').val(),\r\n");
      out.write("\t\t\t\tmaxTotalAmount:$('#searchTotalAmountE').val(),\r\n");
      out.write("\t\t\t\tstartDate:$('#searchRegStartDate').combobox('getValue'),\r\n");
      out.write("\t\t\t\tendDate:$('#searchRegEndDate').combobox('getValue'),\r\n");
      out.write("\t\t\t\tmobilephone:$('#searchRegMobilephone').val(),\r\n");
      out.write("\t\t\t\trealname:$('#searchRegRealname').val(),\r\n");
      out.write("\t\t\t\tcids:cids,\r\n");
      out.write("\t\t\t\tregfrom:regfrom,\r\n");
      out.write("\t\t\t\tisInvest:$('#isInvest').combo(\"getValue\")+\"\",\r\n");
      out.write("\t\t\t\tisCrush:$('#isCrush').combo(\"getValue\")+\"\",\r\n");
      out.write("\t\t\t\tkeyWord:$('#searchRegKeyWord').val(),\r\n");
      out.write("\t\t\t\tlevel:$('#searchMemberCarryLevel').combo(\"getValue\")\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write(" \t\tif($('#searchInvestAmountS').val() =='' &&\r\n");
      out.write("            $('#searchInvestAmountE').val() =='' &&\r\n");
      out.write("            $('#searchTotalAmountS').val() =='' &&\r\n");
      out.write("            $('#searchTotalAmountE').val() =='' &&\r\n");
      out.write("            cids =='' &&\r\n");
      out.write("            regfrom =='' &&\r\n");
      out.write("            $('#searchRegMobilephone').val() =='' &&\r\n");
      out.write("            $('#searchRegRealname').val() =='' &&\r\n");
      out.write("            $('#isInvest').combo(\"getValue\") =='' &&\r\n");
      out.write("            $('#isCrush').combo(\"getValue\") =='' &&\r\n");
      out.write("            $('#searchRegKeyWord').val() =='' &&\r\n");
      out.write("            $('#searchMemberCarryLevel').combo(\"getValue\") ==''\r\n");
      out.write("\t\t){\r\n");
      out.write("           var startDate = $('#searchRegStartDate').combobox('getValue');\r\n");
      out.write("           var endDate = $('#searchRegEndDate').combobox('getValue');\r\n");
      out.write("            var url = \"../regMemberInfo/getTitleParam.do\";\r\n");
      out.write("            if(startDate !='' || endDate!= ''){\r\n");
      out.write("                url = url + \"?startDate=\"+startDate+\"&endDate=\"+endDate;\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("            $.getJSON(url,\r\n");
      out.write("                function(data){\r\n");
      out.write("                    if(data.channel != 1) {\r\n");
      out.write("                        $('#regMemberInfoList').datagrid({\r\n");
      out.write("                            title:\r\n");
      out.write("                            '用户列表 | 平台用户：<font  color=\\'red\\'>' + data.totalPeople + '</font>人' +\r\n");
      out.write("                            '\t投资：<font  color=\\'red\\'>' + data.totalInvest + '</font>人' +\r\n");
      out.write("                            '\t未投资：<font  color=\\'red\\'>' + (data.totalPeople - data.totalInvest) + '</font>人' +\r\n");
      out.write("                            '\t(未绑卡未投资：<font  color=\\'red\\'>' + (data.totalPeople - data.totalInvest - data.haveCardAndUninvest) + '</font>人' +\r\n");
      out.write("                            '，已绑卡未投资：<font  color=\\'red\\'>' + data.haveCardAndUninvest + '</font>人)' +\r\n");
      out.write("                            '\t渠道：<font  color=\\'red\\'>' + data.totalChannel + '</font>个(除七彩格子外)  '\r\n");
      out.write("                        });\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("\t\t}else {\r\n");
      out.write("            $('#regMemberInfoList').datagrid({title:'用户列表'});\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//导出\r\n");
      out.write("\tfunction exportRegMemberInfo(){\r\n");
      out.write("\t\twindow.location.href=\"../regMemberInfo/exportRegMemberInfo.do?realname=\"+encodeURIComponent(encodeURIComponent($('#searchRegRealname').val()))+\r\n");
      out.write("\t\t\t\t\t\t\"&isInvest=\"+$('#isInvest').combo(\"getValue\")+\"\"+\r\n");
      out.write("\t\t\t\t\t\t\"&mobilephone=\"+$('#searchRegMobilephone').val()+\r\n");
      out.write("\t\t\t\t\t\t\"&startDate=\"+$('#searchRegStartDate').combobox('getValue')+\r\n");
      out.write("\t\t\t\t\t\t\"&endDate=\"+$('#searchRegEndDate').combobox('getValue')+\r\n");
      out.write("\t\t\t\t\t\t\"&cids=\"+$('#cid').combogrid('getValues')+\r\n");
      out.write("\t\t\t\t\t\t\"&keyWord=\"+$('#searchRegKeyWord').val()+\"\"+\r\n");
      out.write("\t\t\t\t\t\t\"&isCrush=\"+$('#isCrush').combo(\"getValue\")+\"\"+\r\n");
      out.write("\t\t\t\t\t\t\"&minInvestAmount=\"+$('#searchInvestAmountS').val()+\"\"+\r\n");
      out.write("\t\t\t\t\t\t\"&maxInvestAmount=\"+$('#searchInvestAmountE').val()+\"\"+\r\n");
      out.write("\t\t\t\t\t\t\"&minTotalAmount=\"+$('#searchTotalAmountS').val()+\"\"+\r\n");
      out.write("\t\t\t\t\t\t\"&maxTotalAmount=\"+$('#searchTotalAmountE').val()+\"\"+\r\n");
      out.write("\t\t\t\t\t\t\"&regfrom=\"+$('#regfrom').combogrid('getValues');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//是否是VIP\r\n");
      out.write("\tfunction formaterVIP(value,row,index){\r\n");
      out.write("\t\tif(row.level == \"1\"){\r\n");
      out.write("\t\t\treturn 'VIP';\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\treturn '普通用户';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("    window.onload=function(){\r\n");
      out.write("        var date = new Date();\r\n");
      out.write("        var month = date.getMonth() + 1;\r\n");
      out.write("        var strDate = date.getDate();\r\n");
      out.write("        if (month >= 1 && month <= 9) {\r\n");
      out.write("            month = \"0\" + month;\r\n");
      out.write("        }\r\n");
      out.write("        if (strDate >= 0 && strDate <= 9) {\r\n");
      out.write("            strDate = \"0\" + strDate;\r\n");
      out.write("        }\r\n");
      out.write("        var currentdate = date.getFullYear() +\"-\"+ month  +\"-\"+ strDate;\r\n");
      out.write("        $.getJSON(\"../regMemberInfo/getTitleParam.do?startDate=\"+currentdate, function(data){\r\n");
      out.write("            if(data.channel != 1){\r\n");
      out.write("                $('#regMemberInfoList').datagrid({title:\r\n");
      out.write("                    '用户列表 | 平台用户：<font  color=\\'red\\'>'+data.totalPeople+'</font>人'+\r\n");
      out.write("                    '\t投资：<font  color=\\'red\\'>'+data.totalInvest+'</font>人'+\r\n");
      out.write("                    '\t未投资：<font  color=\\'red\\'>'+(data.totalPeople-data.totalInvest)+'</font>人'+\r\n");
      out.write("                    '\t(未绑卡未投资：<font  color=\\'red\\'>'+(data.totalPeople-data.totalInvest-data.haveCardAndUninvest)+'</font>人'+\r\n");
      out.write("                    '，已绑卡未投资：<font  color=\\'red\\'>'+data.haveCardAndUninvest+'</font>人)'+\r\n");
      out.write("                    '\t渠道：<font  color=\\'red\\'>'+data.totalChannel+'</font>个(除七彩格子外)  '\r\n");
      out.write("                });\r\n");
      out.write("\t\t\t}\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $('#searchRegStartDate').datebox('setValue', currentdate);\r\n");
      out.write("        $('#searchRegEndDate').datebox('setValue', currentdate);\r\n");
      out.write("\r\n");
      out.write("        $('#regMemberInfoList').datagrid({\r\n");
      out.write("            url: '../regMemberInfo/regMemberInfoList.do',\r\n");
      out.write("            queryParams: {\r\n");
      out.write("                startDate:currentdate,\r\n");
      out.write("                endDate:currentdate\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/jsp/system/orderManager/regMemberInfoList.jsp(75,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/system/orderManager/regMemberInfoList.jsp(75,6) '${level }'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${level }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/jsp/system/orderManager/regMemberInfoList.jsp(75,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("map");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<option value='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.key }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('\'');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${map.value }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
