server:
  port: 8762
eureka:
  instance:
    hostname: localhost
  server: 
    enableSelfPreservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: service-gg
spring.rabbitmq: 
   host: 192.168.56.102 
   port: 5672  
   username: admin  
   password: admin  

