/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2018-05-30 08:11:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.background.electric;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class staffList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/background/electric/../../common/util.jsp", Long.valueOf(1527667097148L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/validatebox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/common.js\"></script>");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery.form.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<table id=\"crmstaffList\" title=\"电销专员\" \r\n");
      out.write("\tclass=\"easyui-datagrid\" style=\"height:99%;\" remoteSort=\"true\"\r\n");
      out.write("\tdata-options=\"singleSelect:true,\r\n");
      out.write("\t    fitColumns:true, url: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/background/electric/staffList.html',\r\n");
      out.write("\t    method:'post',rownumbers:true, \r\n");
      out.write("\t    pagination:true,toolbar:'#drProductInvestTools'\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t    <tr>\r\n");
      out.write("<!-- \t    \t<th data-options=\"checkbox:true\"></th> -->\r\n");
      out.write("\t    \t<th data-options=\"field:'uid'\" width=\"80px\">用户ID</th>\r\n");
      out.write("\t        <th data-options=\"field:'userName'\"  width=\"80px\">用户姓名</th>\r\n");
      out.write("\t        <th data-options=\"field:'mobilePhone'\" formatter=\"formatImg\" width=\"80px\">手机号</th>\r\n");
      out.write("\t        <th data-options=\"field:'mobile'\" width=\"80px\">手机号</th>\r\n");
      out.write("\t        <th data-options=\"field:'referrerName'\"  width=\"80px\">推荐人姓名</th>\r\n");
      out.write("\t        <th data-options=\"field:'referrerPhone'\"  width=\"80px\"  formatter=\"formatRef\">推荐人号码</th>\r\n");
      out.write("\t        <th data-options=\"field:'registertime'\" width=\"80px\" formatter=\"formatDateBoxFull\">注册时间</th>\r\n");
      out.write("\t        <th data-options=\"field:'bankName'\" width=\"80px\">绑卡银行</th>\r\n");
      out.write("\t        <th data-options=\"field:'balance'\" sortable=\"true\" styler=\"styleColor\" width=\"80px\">账户金额</th>\r\n");
      out.write("\t        <th data-options=\"field:'freeze'\" sortable=\"true\" styler=\"styleColor\" width=\"80px\">冻结金额</th>\r\n");
      out.write("\t        <th data-options=\"field:'wprincipal'\" sortable=\"true\" styler=\"styleColor\" width=\"80px\">待收本金</th>\r\n");
      out.write("\t        <th data-options=\"field:'investAmount'\" sortable=\"true\" styler=\"styleColor\" width=\"80px\">累计投资总额</th>\r\n");
      out.write("\t        <th data-options=\"field:'isFollow'\"  width=\"80px\" formatter=\"formatFollow\">是否沟通</th>\r\n");
      out.write("\t        <th data-options=\"field:'followCount'\" sortable=\"true\"  width=\"50px\">沟通次数</th>\r\n");
      out.write("\t        <th data-options=\"field:'lastFollowTime'\"  width=\"100px\"  formatter=\"formatDateBoxFull\">最后沟通时间</th>\r\n");
      out.write("\t\t\t<th data-options=\"field:'lastFollowState'\" width=\"100px\">最后沟通状态</th>\r\n");
      out.write("\t        <th data-options=\"field:'regfrom'\"  width=\"80px\" formatter=\"formatRegfrom\">注册终端</th>\r\n");
      out.write("\t        <th data-options=\"field:'_operate',align:'center'\"  width=\"80px\"  formatter=\"formatOper\">操作</th>\r\n");
      out.write("\t    </tr>\r\n");
      out.write("\t    </thead>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div id=\"drProductInvestTools\" style=\"padding:5px;height:750\">\r\n");
      out.write("\t  \t<form id=\"staffListForm\">\r\n");
      out.write("\t  \t\t手机号:<input id=\"searchRegMobilephone\" name=\"mobilephone\" class=\"easyui-textbox\"  size=\"30\" style=\"width:100px\"/>\r\n");
      out.write("\t  \t\t用户姓名:<input id=\"searchRegRealname\" name=\"userName\" class=\"easyui-textbox\"  size=\"30\" style=\"width:100px\"/>\r\n");
      out.write("\t  \t\t注册日期:<input id=\"searchRegStartDate\" name=\"dateStart\" class=\"easyui-datebox\" style=\"width:100px\"/>到\r\n");
      out.write("\t  \t\t\t\t<input id=\"searchRegEndDate\" name=\"dateEnd\" class=\"easyui-datebox\" style=\"width:100px\"/>\r\n");
      out.write("\t\t\t预约时间:<input id=\"searchAdvanceDate\" name=\"advanceDate\" class=\"easyui-datebox\" style=\"width:100px\"/>\r\n");
      out.write("\t\t\t推荐人姓名:<input id=\"searchDrProductInvestRecomRealName\" name=\"referrerName\" class=\"easyui-textbox\" value=\"\" size=\"30\" style=\"width:100px\"/>\r\n");
      out.write("\t  \t\t推荐人号码:<input id=\"searchDrProductInvestRecomMobilePhone\" name=\"referrerPhone\" class=\"easyui-textbox\"  size=\"30\" style=\"width:100px\"/>\r\n");
      out.write("\t  \t\t累计投资额:<input id=\"searchInvestAmountS\" name=\"minAmount\" class=\"easyui-textbox\" value=\"\" size=\"30\" style=\"width:100px\"/>&nbsp;至\r\n");
      out.write("\t\t\t\t\t<input id=\"searchInvestAmountE\" name=\"maxAmount\" class=\"easyui-textbox\" value=\"\" size=\"30\" style=\"width:100px\"/><br/>\r\n");
      out.write("\t\t\t是否投资:<select id=\"isInvest\" class=\"easyui-combobox\" name=\"isInvest\" style=\"width:200px;\">   \r\n");
      out.write("\t\t\t\t\t    <option value=\"\">全部</option>   \r\n");
      out.write("\t\t\t\t\t    <option value=\"1\">是</option>   \r\n");
      out.write("\t\t\t\t\t    <option value=\"0\">否</option>   \r\n");
      out.write("\t\t\t\t\t</select> \r\n");
      out.write("\t\t\t是否沟通:<select id=\"isFollow\" class=\"easyui-combobox\" name=\"isFollow\" style=\"width:200px;\">   \r\n");
      out.write("\t\t\t\t\t    <option value=\"\">全部</option>   \r\n");
      out.write("\t\t\t\t\t    <option value=\"1\">是</option>   \r\n");
      out.write("\t\t\t\t\t    <option value=\"2\">否</option>   \r\n");
      out.write("\t\t\t\t\t</select>\t\t\r\n");
      out.write("\t\t\t跟进流程状态：<select id=\"status\" class=\"easyui-combobox\" name=\"status\" style=\"width:200px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">全部</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0\">未接听</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">待联系</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">持续跟进</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">高意向</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"4\">成功</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"5\">失败</option>\r\n");
      out.write("\t\t\t\t\t\t </select>\t\t\t\t \t\t\t\t\t\t\t\r\n");
      out.write("\t    \t<a id=\"search\" href=\"javascript:void(0)\" class=\"easyui-linkbutton\" iconCls=\"icon-search\">查询</a>\r\n");
      out.write("\t    \t<a id=\"reset\" href=\"javascript:void(0)\" class=\"easyui-linkbutton\" iconCls=\"icon-reload\">重置</a>\r\n");
      out.write("\t    </form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"w\" class=\"easyui-dialog\" title=\"沟通管理\" data-options=\"iconCls:'icon-save',minimizable:false,tools:'#tt',closed:true\" style=\"width:600px;height:400px;padding:10px;\">\r\n");
      out.write("<!-- \t\t<div align=\"center\">用户姓名：<span id=\"userName\"></span> -->\r\n");
      out.write("<!-- \t\t&nbsp;&nbsp;&nbsp;手机号：<span id=\"mobilePhone\"></span> -->\r\n");
      out.write("<!-- \t\t<a href=\"#\" class=\"btn l-btn l-btn-small\"  onclick=\"clickPhone()\">呼叫</a></div><br> -->\r\n");
      out.write("<!-- \t\t<div id=\"ztth_load\"></div> -->\r\n");
      out.write("<!-- \t\t<script> -->\r\n");
      out.write("<!--    \t\t    var ag_num_value = 8001;   -->\r\n");
      out.write("<!--   \t\t    var ag_phone_value = 15909346841;   -->\r\n");
      out.write("\r\n");
      out.write("<!--  \t\t</script>  -->\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$('#crmstaffList').datagrid(\"hideColumn\", \"mobile\");\r\n");
      out.write("\t});\r\n");
      out.write("\t//查询按钮\r\n");
      out.write("\t$('#search').click(function(sort,order){\r\n");
      out.write(" \t\t$('#crmstaffList').datagrid({\r\n");
      out.write("\t\t\tqueryParams: {\r\n");
      out.write("\t\t\t\tminAmount:$('#searchInvestAmountS').val(),\r\n");
      out.write("\t\t\t\tmaxAmount:$('#searchInvestAmountE').val(),\r\n");
      out.write("\t\t\t\tdateStart:$('#searchRegStartDate').combobox('getValue'),\r\n");
      out.write("\t\t\t\tdateEnd:$('#searchRegEndDate').combobox('getValue'),\r\n");
      out.write("\t\t\t\tadvanceDate:$('#searchAdvanceDate').combobox('getValue'),\r\n");
      out.write("\t\t\t\tmobilePhone:$('#searchRegMobilephone').val(),\r\n");
      out.write("\t\t\t\tuserName:$('#searchRegRealname').val(),\r\n");
      out.write("\t\t\t\treferrerName:$('#searchDrProductInvestRecomRealName').val(),\r\n");
      out.write("\t\t\t\tisInvest:$('#isInvest').combo(\"getValue\")+\"\",\r\n");
      out.write("\t\t\t\tisFollow:$('#isFollow').combo(\"getValue\")+\"\",\r\n");
      out.write("\t\t\t\tstatus:$('#status').combo(\"getValue\")+\"\",\r\n");
      out.write("\t\t\t\treferrerPhone:$('#searchDrProductInvestRecomMobilePhone').val()\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}); \r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction formatImg(val,row,index){\r\n");
      out.write("\t\tvar mobile = row.mobilePhone.substr(0, 3)+ '***'+ row.mobilePhone.substr(7);\r\n");
      out.write("\t\treturn  mobile +'<a href=\"#\" onclick=\"clickPhone('+index+')\"><img style=\"width:20px; height:20px\" src=\"../../images/phone.png\"></a>';\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction formatRef(val,row,index){\r\n");
      out.write("\t\tvar mobile = row.referrerPhone;\r\n");
      out.write("\t\tif(mobile!=null&&mobile!=''){\r\n");
      out.write("\t\t\tmobile=mobile.substr(0, 3)+ '***'+ mobile.substr(7);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn  mobile;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction formatFollow(val,row,index){\r\n");
      out.write("\t\tvar val = row.followCount;\r\n");
      out.write("\t\tif(val>=1){return '是';}\r\n");
      out.write("\t\telse{return '否';}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction formatRegfrom(val,row,index){\r\n");
      out.write("\t\tif(val==0){return 'pc';}\r\n");
      out.write("\t\telse if(val == 1){return 'IOS';}\r\n");
      out.write("\t\telse if(val == 2){return 'android';}\r\n");
      out.write("\t\telse if(val == 3){return '微信';}\r\n");
      out.write("\t\telse if(val == 4){return 'WAP';}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//重置\r\n");
      out.write("\t$('#reset').click(function(){\r\n");
      out.write("\t\t$(\"#staffListForm\").form(\"reset\");\r\n");
      out.write("\t\t$(\"#crmstaffList\").datagrid(\"load\", {});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//沟通记录窗口\r\n");
      out.write("// \tfunction clickPhone(index){\r\n");
      out.write("// \t\tvar row = $('#crmstaffList').datagrid('getSelected'); \r\n");
      out.write("// \t\t$(\"#userName\").text(row.userName);\r\n");
      out.write("// \t\t$(\"#mobilePhone\").text(row.mobilePhone);\r\n");
      out.write("// \t\t$('#followList').datagrid({\r\n");
      out.write("// \t\t\turl: '../electric/staffList.html?mobilePhone='+row.mobilePhone\r\n");
      out.write("// \t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("// \t\t$(\"#w\").window(\"open\");\r\n");
      out.write("// \t\t$('#followList').form('load', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/background/electric/followList.html?uid=' + row.uid);\r\n");
      out.write("// \t}\r\n");
      out.write("\tfunction clickPhone(index){\r\n");
      out.write("\t\t$('#crmstaffList').datagrid('selectRow',index);// 关键在这里 \r\n");
      out.write("\t\tvar row = $('#crmstaffList').datagrid('getSelected'); \r\n");
      out.write("\t\tvar userName =row.userName;\r\n");
      out.write("\t\tvar mobilePhone = row.mobile;\r\n");
      out.write("\t\tvar mobile = row.mobilePhone;\r\n");
      out.write("\t\t$(\"#w\").window({\r\n");
      out.write("\t\t\ttitle:\"沟通管理\",\r\n");
      out.write("\t\t\twidth:$(this).width()*0.5,\r\n");
      out.write("\t\t\theight:$(this).height()*0.6,\r\n");
      out.write("\t\t\tmaximizable:true,\r\n");
      out.write("\t\t\thref:'../electric/toFollowList.html?uid=' + row.uid + '&userName='+userName+'&mobilePhone='+mobilePhone+'&mobile='+mobile,\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#w\").window(\"open\").window(\"center\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//添加基本操作链接\r\n");
      out.write("\tfunction formatOper(val,row,index){  \r\n");
      out.write("// \t\treturn\t'<button type=\"button\" class=\"btn\" id=\"ztth_callouter_btn\" onclick=\"clickOutNum()\"> 呼叫</button>&nbsp;&nbsp;&nbsp;';\r\n");
      out.write("\t\treturn '<a href=\"#\" class=\"btn l-btn l-btn-small\"  onclick=\"clickPhone('+index+')\">沟通</a>&nbsp;&nbsp;&nbsp;';\r\n");
      out.write("\t} \r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
