server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
spring:
  application:
    name: service-gg
spring.rabbitmq: 
   host: 192.168.56.102 
   port: 5672  
   username: admin  
   password: admin  

