/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2018-04-08 02:51:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.system.sys;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/common/include/Taglibs.jsp", Long.valueOf(1523153962924L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    response.setHeader("Content-Type","text/html; charset=utf-8");
    request.setCharacterEncoding("utf-8");
    pageContext.setAttribute("pageEncoding","utf-8");
    
	String apppath = request.getContextPath();
	request.setAttribute("apppath", apppath);
	
	Date d = new Date();
	String tabid = "tabid"+d.getTime();
	request.setAttribute("tabid", tabid);

      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"description\" content=\"内容描述\">\r\n");
      out.write("<meta name=\"author\" content=\"作者\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/work.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/common.css\" />\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tif(window!=top){\r\n");
      out.write("\t\ttop.location.href=location.href;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"login-wrap\">\r\n");
      out.write("\t<h1 class=\"logo\">\r\n");
      out.write("    \t<a href=\"http://www.77color.com/\" target=\"_Blank\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/login-logo.png\" /></a>\r\n");
      out.write("    </h1>\r\n");
      out.write("    <div class=\"title\">管理系统<i>Management System</i></div>\r\n");
      out.write("    <div class=\"login-box\">\r\n");
      out.write("    \t<form id=\"loginForm\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/doLoginUser.do\" id=\"loginForm\"  method=\"post\">\r\n");
      out.write("        \t<label class=\"username\"><i></i>\r\n");
      out.write("\t        \t<p>用户名</p>\r\n");
      out.write("\t        \t<input id=\"loginId\" type=\"text\" name=\"loginId\"/>\r\n");
      out.write("        \t</label>\r\n");
      out.write("        \t<span id=\"loginText\" style=\"display: none;color: #fe6a6a\">请输入用户名</span>\r\n");
      out.write("            <label class=\"passwd\"><i></i>\r\n");
      out.write("            \t<p>密 &nbsp; 码</p>\r\n");
      out.write("            \t<input id=\"password\" type=\"password\" name=\"password\"/>\r\n");
      out.write("            </label>\r\n");
      out.write("           \t<span id=\"pwdText\" style=\"display: none;color: #fe6a6a\">请输入密码</span>\r\n");
      out.write("            <div class=\"code-wrap\">\r\n");
      out.write("            \t<label class=\"code\"><i></i>\r\n");
      out.write("\t            \t<p>验证码</p>\r\n");
      out.write("\t            \t<input id=\"randCode\" name=\"randCode\" type=\"text\" />\r\n");
      out.write("            \t</label>\r\n");
      out.write("            \t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/validateCode.do\" onclick=\"this.src=this.src+'?'\" />\r\n");
      out.write("            </div>\r\n");
      out.write("           \t<span id=\"codeText\" style=\"display: none;color: #fe6a6a\"></span>\r\n");
      out.write("            <div class=\"sub-wrap\">\r\n");
      out.write("            \t<input class=\"sub\" value=\"登 &nbsp; 录\"  onclick=\"login()\" type=\"button\" />\r\n");
      out.write("            </div>  \r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"foot-wrap\"><span>@版权所有</span><a class=\"name\" href=\"#\">上海探禄网络科技有限公司</a></div>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\"#loginId\").blur(function(){\r\n");
      out.write("\t\tif($(\"#loginId\").val().length <= 0){\r\n");
      out.write("\t\t\t$(\"#loginText\").show();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#loginText\").hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#password\").blur(function(){\r\n");
      out.write("\t\tif($(\"#password\").val().length <= 0){\r\n");
      out.write("\t\t\t$(\"#pwdText\").show();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#pwdText\").hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#randCode\").blur(function(){\r\n");
      out.write("\t\tif($(\"#randCode\").val().length <= 0){\r\n");
      out.write("\t\t\t$(\"#codeText\").html(\"请输入验证码\");\r\n");
      out.write("\t\t\t$(\"#codeText\").show();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#codeText\").hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\tfunction login(){\r\n");
      out.write("\t\t$(\"#codeText\").css(\"display\",\"none\").html(\"\");\r\n");
      out.write("\t\t$(\"#pwdText\").css(\"display\",\"none\");\r\n");
      out.write("\t\t$(\"#loginText\").css(\"display\",\"none\");\r\n");
      out.write("\t\tvar loginId = $(\"form input:eq(0)\").val();\r\n");
      out.write("\t\tvar password =  $(\"form input:eq(1)\").val();\r\n");
      out.write("\t\tvar loginErrorNums = $(\"#loginErrorNums\").val();\r\n");
      out.write("\t\tvar randCode = $(\"#randCode\").val();\r\n");
      out.write("\t\tif(loginId == \"\"){\r\n");
      out.write("\t\t\t$(\"#loginText\").css(\"display\",\"block\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(password == \"\"){\r\n");
      out.write("\t\t\t$(\"#pwdText\").css(\"display\",\"block\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(randCode == \"\"){\r\n");
      out.write("\t\t\t$(\"#codeText\").css(\"display\",\"block\").html(\"请输入验证码\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/checkCode.do\",\r\n");
      out.write("\t\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\t\tdata:{\"randCode\":randCode},\r\n");
      out.write("\t\t\t\tsuccess: function(result){\r\n");
      out.write("\t\t\t\t\tif(result.msg){\r\n");
      out.write("\t\t\t\t\t\t$(\"#loginForm\").submit();\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$(\"#codeText\").css(\"display\",\"block\").html(\"验证码不正确\");\r\n");
      out.write("\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\tjQuery(document).keydown(function (event) {\r\n");
      out.write("\t\t    if(event.keyCode==13){\r\n");
      out.write("\t\t    \tlogin();\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t }); \r\n");
      out.write("\t</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
