/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2018-04-08 02:57:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.system.sys;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;

public final class menuList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/jsp/system/sys/../../common/include/util.jsp", Long.valueOf(1523153962925L));
    _jspx_dependants.put("/WEB-INF/jsp/common/include/Taglibs.jsp", Long.valueOf(1523153962924L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005fid_005faction;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005fid_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005fid_005faction.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    response.setHeader("Content-Type","text/html; charset=utf-8");
    request.setCharacterEncoding("utf-8");
    pageContext.setAttribute("pageEncoding","utf-8");
    
	String apppath = request.getContextPath();
	request.setAttribute("apppath", apppath);
	
	Date d = new Date();
	String tabid = "tabid"+d.getTime();
	request.setAttribute("tabid", tabid);

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\t<meta name=\"description\" content=\"内容描述\">\r\n");
      out.write("\t<meta name=\"author\" content=\"作者\">\r\n");
      out.write("\t");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/validatebox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/common/common.js\"></script>");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar status = [{\"value\":\"1\",\"text\":\"可用\"},{\"value\":\"0\",\"text\":\"禁用\"}];\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t\t$(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tabid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" #tg\").treegrid({\r\n");
      out.write("\t\t\t\turl:\"../menu/menuList.do\",\r\n");
      out.write("\t\t\t\tidField:\"menuKy\",\r\n");
      out.write("\t\t\t\ttreeField:\"name\", \r\n");
      out.write("\t\t\t\tcollapsible: true,\r\n");
      out.write("\t\t\t\tcolumns:[[\r\n");
      out.write("\t\t\t\t  {title:'编号',field:'menuKy',width:$(this).width() * 0.05,align:'right'},\r\n");
      out.write("\t\t          {title:'菜单名称',field:'name',width:$(this).width() * 0.2,align:'center',editor:\"text\"},\r\n");
      out.write("\t\t          {title:'URL地址',field:'url',width:$(this).width() * 0.2,align:'center',editor:\"text\"},\r\n");
      out.write("\t\t          {title:'菜单级别',field:'grade',width:$(this).width() * 0.1,align:'center',editor:\"numberbox\"},\r\n");
      out.write("\t\t          {title:'父菜单编号',field:'parent',width:$(this).width() * 0.05,align:'center',editor:\"text\"},\r\n");
      out.write("\t\t          {title:'位置序号',field:'position',width:$(this).width() * 0.05,align:'center',editor:\"text\"},\r\n");
      out.write("\t\t          {title:'状态',field:'status',width:$(this).width() * 0.2,align:'left',editor:{type:'combobox',options: {data:status,textField:'text',valueField:'value' }},\r\n");
      out.write("\t\t        \t  formatter:function(value,rec){\r\n");
      out.write("\t\t        \t  \t\tif(rec.status=='0'){\r\n");
      out.write("\t\t        \t  \t\t\treturn \"禁用\";\r\n");
      out.write("\t\t        \t  \t\t}else{\r\n");
      out.write("\t\t        \t  \t\t\treturn \"可用\";\r\n");
      out.write("\t\t        \t  \t\t}\r\n");
      out.write("\t\t\t\t\t\t}  \r\n");
      out.write("\t\t          }\r\n");
      out.write("\t\t\t\t]]\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tabid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t<div style=\"margin:20px 0;\">\r\n");
      out.write("\t\t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"javascript:$('#window').window('open');\">菜单录入</a>\r\n");
      out.write("\t\t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"edit()\">编辑</a>\r\n");
      out.write("\t\t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"save()\">保存</a>\r\n");
      out.write("\t\t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"cancel()\">取消</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<table id=\"tg\" class=\"easyui-treegrid\" style=\"height: 500px;\"></table>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"window\" class=\"easyui-window\" title=\"菜单录入\" \r\n");
      out.write("\t\tdata-options=\"iconCls:'icon-add',closed:true,minimizable:false,resizable:false,maximizable:false\" style=\"width:700px;height:400px;padding:10px;\">\r\n");
      out.write("\t\t<div style=\"padding:10px 60px 20px 60px\">\r\n");
      out.write("\t\t");
      if (_jspx_meth_form_005fform_005f0(_jspx_page_context))
        return;
      out.write("<div style=\"text-align:center;padding:5px\">\r\n");
      out.write("\t    \t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"submitForm()\">添加</a>\r\n");
      out.write("\t    \t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"clearForm()\">清空</a>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar editingId;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction edit(){\r\n");
      out.write("\t\t\tif (editingId != undefined){\r\n");
      out.write("\t\t\t\t$(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tabid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" #tg\").treegrid('select', editingId);\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar row = $(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tabid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" #tg\").treegrid('getSelected');\r\n");
      out.write("\t\t\tif (row){\r\n");
      out.write("\t\t\t\teditingId = row.menuKy;\r\n");
      out.write("\t\t\t\t$('#tg').treegrid('beginEdit', editingId);\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\talert(\"请选择要修改的行\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction save(){\r\n");
      out.write("\t\t\tif (editingId != undefined){\r\n");
      out.write("\t\t\t\tvar t = $(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tabid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" #tg\");\r\n");
      out.write("\t\t\t\tvar update = t.treegrid('endEdit', editingId);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar rows = eval(t.treegrid('getSelected'));\r\n");
      out.write("\t\t\t\tif(rows.menuKy==editingId){\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl: \"../menu/updateMenu.do\",\r\n");
      out.write("\t\t\t\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\t\t\t\tdata : {\"str\":JSON.stringify(rows)},\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(result){\r\n");
      out.write("\t\t\t\t\t\t\tif(result == \"success\"){\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"修改成功\");\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"修改失败\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\teditingId = undefined;\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction cancel(){\r\n");
      out.write("\t\t\tif (editingId != undefined){\r\n");
      out.write("\t\t\t\t$(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tabid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" #tg\").treegrid('cancelEdit', editingId);\r\n");
      out.write("\t\t\t\teditingId = undefined;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction submitForm(){\r\n");
      out.write("\t\t\tif($(\"#addform\").form('enableValidation').form('validate')){\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/menu/addMenu.do\",\r\n");
      out.write("\t\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\t\t\tdata:$(\"#addform\").serialize(),\r\n");
      out.write("\t\t\t\t\tasync:false,\r\n");
      out.write("\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\t$.messager.alert(\"提示信息\",\"添加成功！\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#addform\").form('clear');\r\n");
      out.write("\t\t\t\t$(\"#window\").window('close');\r\n");
      out.write("\t\t\t\t$(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tabid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" #tg\").treegrid(\"reload\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction clearForm(){\r\n");
      out.write("\t\t\t$(\"#addform\").form('clear');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_form_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005fid_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005fform_005f0.setParent(null);
    // /WEB-INF/jsp/system/sys/menuList.jsp(54,2) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setId("addform");
    // /WEB-INF/jsp/system/sys/menuList.jsp(54,2) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setAction("../menu/addMenu.do");
    // /WEB-INF/jsp/system/sys/menuList.jsp(54,2) name = modelAttribute type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setModelAttribute("sysMenu");
    // /WEB-INF/jsp/system/sys/menuList.jsp(54,2) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setMethod("post");
    int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
      if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<table cellpadding=\"5\">\r\n");
          out.write("\t    \t\t<tr>\r\n");
          out.write("\t    \t\t\t<td>菜单名称:</td>\r\n");
          out.write("\t    \t\t\t<td><input class=\"easyui-textbox\" type=\"text\" name=\"name\" data-options=\"required:true\"></input></td>\r\n");
          out.write("\t    \t\t</tr>\r\n");
          out.write("\t    \t\t<tr>\r\n");
          out.write("\t    \t\t\t<td>URL地址:</td>\r\n");
          out.write("\t    \t\t\t<td><input class=\"easyui-textbox\" type=\"text\" name=\"url\"></input></td>\r\n");
          out.write("\t    \t\t</tr>\r\n");
          out.write("\t    \t\t<tr>\r\n");
          out.write("\t    \t\t\t<td>菜单级别:</td>\r\n");
          out.write("\t    \t\t\t<td>\r\n");
          out.write("\t    \t\t\t\t<select name=\"grade\">\r\n");
          out.write("\t    \t\t\t\t\t<option value=\"1\">一级菜单</option>\r\n");
          out.write("\t    \t\t\t\t\t<option value=\"2\">二级菜单</option>\r\n");
          out.write("\t    \t\t\t\t\t<option value=\"3\">三级菜单</option>\r\n");
          out.write("\t    \t\t\t\t</select>\r\n");
          out.write("\t    \t\t\t</td>\r\n");
          out.write("\t    \t\t</tr>\r\n");
          out.write("\t    \t\t<tr>\r\n");
          out.write("\t    \t\t\t<td>父菜单编号:</td>\r\n");
          out.write("\t    \t\t\t<td>\r\n");
          out.write("\t\t\t\t\t\t<input class=\"easyui-textbox\" type=\"text\" name=\"parent\" data-options=\"required:true\"></input>\r\n");
          out.write("\t    \t\t\t</td>\r\n");
          out.write("\t    \t\t</tr>\r\n");
          out.write("\t    \t\t<tr>\r\n");
          out.write("\t    \t\t\t<td>状态:</td>\r\n");
          out.write("\t    \t\t\t<td>\r\n");
          out.write("\t    \t\t\t\t<select name=\"status\">\r\n");
          out.write("\t    \t\t\t\t\t<option value=\"1\">可用</option>\r\n");
          out.write("\t    \t\t\t\t\t<option value=\"0\">禁用</option>\r\n");
          out.write("\t    \t\t\t\t</select>\r\n");
          out.write("\t    \t\t\t</td>\r\n");
          out.write("\t    \t\t</tr>\r\n");
          out.write("\t\t\t</table>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005fform_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005fform_0026_005fmodelAttribute_005fmethod_005fid_005faction.reuse(_jspx_th_form_005fform_005f0);
    }
    return false;
  }
}
