/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2018-03-27 03:41:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.system.article;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class sysArticleList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/common/include/Taglibs.jsp", Long.valueOf(1521710765618L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    response.setHeader("Content-Type","text/html; charset=utf-8");
    request.setCharacterEncoding("utf-8");
    pageContext.setAttribute("pageEncoding","utf-8");
    
	String apppath = request.getContextPath();
	request.setAttribute("apppath", apppath);
	
	Date d = new Date();
	String tabid = "tabid"+d.getTime();
	request.setAttribute("tabid", tabid);

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/validatebox.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<table id=\"articleList\" title=\"文章列表 \" \r\n");
      out.write("\tclass=\"easyui-datagrid\" style=\"height:99%;width:99.9%\"\r\n");
      out.write("\tdata-options=\"singleSelect:true,\r\n");
      out.write("\t    fitColumns:true, url: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/article/articleList.do',\r\n");
      out.write("\t    method:'post',rownumbers:true, \r\n");
      out.write("\t    pagination:true,toolbar:'#articleTools',onLoadSuccess:articleBtn\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t    <tr>\r\n");
      out.write("\t    \t<th data-options=\"field:'artiId'\" width=\"10%\" hidden=\"true\">ID</th>\r\n");
      out.write("\t    \t<th data-options=\"field:'isrecommend'\" width=\"10%\" hidden=\"true\">推荐</th>\r\n");
      out.write("\t        <th data-options=\"field:'title'\" width=\"20%\">文章标题</th>\r\n");
      out.write("\t        <th data-options=\"field:'proName'\" width=\"10%\">栏目</th>\r\n");
      out.write("\t       \t<th data-options=\"field:'ishead'\" width=\"3%\" formatter=\"formatIsHead\">头条</th>\r\n");
      out.write("\t       \t<th data-options=\"field:'createName'\" width=\"10%\">创建人</th>\t     \r\n");
      out.write("\t       \t<th data-options=\"field:'updateName'\" width=\"10%\">最后操作人</th>\r\n");
      out.write("\t       \t<th data-options=\"field:'updateTime'\" width=\"10%\" formatter=\"formatDate\">最后编辑时间</th>\t      \t\r\n");
      out.write("\t\t\t<th data-options=\"field:'createTime'\" width=\"10%\" formatter=\"formatDate\">发布时间</th>\r\n");
      out.write("\t\t\t<th data-options=\"field:'status'\" width=\"3%\" formatter=\"formatStatus\">状态</th>\r\n");
      out.write("\t\t\t<th data-options=\"field:'_operate',width:80,align:'center',formatter:formatOper\" width=\"20%\">基本操作</th>\r\n");
      out.write("\t    </tr>\r\n");
      out.write("\t    </thead>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div id=\"articleTools\" style=\"padding:5px;height:750\">\r\n");
      out.write("\t  \t<form id=\"articleForm\">\r\n");
      out.write("\t  \t\t所属栏目: <select  id=\"searchArticleProId\" name=\"proId\" style=\"width:100px;\" class=\"easyui-combobox\">\r\n");
      out.write("\t\t\t\t \t<option value=''>全部</option>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("</select>\r\n");
      out.write("\t  \t\t发布时间:<input id=\"searchArticleStartDate\" name=\"startDate\" class=\"easyui-datetimebox\" style=\"width:150px\"/>\r\n");
      out.write("\t  \t\t至<input id=\"searchArticleEndDate\" name=\"endDate\" class=\"easyui-datetimebox\" style=\"width:150px\"/>\r\n");
      out.write("\t  \t\t文章标题:<input id=\"searchArticleTitle\" name=\"title\" class=\"easyui-textbox\"  size=\"15\" style=\"width:200px\"/>\r\n");
      out.write("\t\t\t是否头条: <select  id=\"searchArticleIshead\" name=\"ishead\" style=\"width:100px;\" class=\"easyui-combobox\">\r\n");
      out.write("\t\t\t\t \t<option value=''>全部</option>\r\n");
      out.write("\t\t\t\t\t<option value='0'>否</option>\r\n");
      out.write("\t\t\t\t\t<option value='1'>是</option>\r\n");
      out.write("\t           \t\t</select>\r\n");
      out.write("\t    \t<a id=\"searchArticleBtn\" href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-search\">查询</a>\r\n");
      out.write("\t    \t<a id=resetArticleBtn href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-reload\">重置</a>\r\n");
      out.write("\t    \t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" iconCls=\"icon-add\" onclick=\"addArticleBtn()\">新增文章</a>\r\n");
      out.write("\t    </form>\r\n");
      out.write("\t</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction articleBtn (){\r\n");
      out.write("\t\t\t$('.articleBtn').linkbutton();\r\n");
      out.write("\t}\r\n");
      out.write("\t//时间格式\r\n");
      out.write("\tfunction formatDate(value,row,index){ \r\n");
      out.write("\t\tif(value == null){\r\n");
      out.write("\t\t\treturn \"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar unixTimestamp = new Date(value);  \r\n");
      out.write("\t\treturn unixTimestamp.toLocaleString();  \r\n");
      out.write("\t} \r\n");
      out.write("\t//重置按钮\r\n");
      out.write("\t$('#resetArticleBtn').click(function(){\r\n");
      out.write("\t\t$(\"#articleForm\").form(\"reset\");\r\n");
      out.write("\t\t$(\"#articleList\").datagrid(\"load\", {});\r\n");
      out.write("\t});\r\n");
      out.write("\t//查询按钮\r\n");
      out.write("\t$('#searchArticleBtn').click(function(){\r\n");
      out.write(" \t\t$('#articleList').datagrid({\r\n");
      out.write("\t\t\tqueryParams: {\r\n");
      out.write("\t\t\t\tstartDate: $('#searchArticleStartDate').datebox('getValue'),\r\n");
      out.write("\t\t\t\tendDate: $('#searchArticleEndDate').datebox('getValue'),\r\n");
      out.write("\t\t\t\ttitle: $('#searchArticleTitle').val(),\r\n");
      out.write("\t\t\t\tishead: $('#searchArticleIshead').combobox(\"getValue\"),\r\n");
      out.write("\t\t\t\tproId: $('#searchArticleProId').combobox(\"getValue\"),\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}); \r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//添加基本操作链接\r\n");
      out.write("\tfunction formatOper(val,row,index){ \r\n");
      out.write("\t\tvar articleOper = '<a href=\"#\" class=\"articleBtn\" onclick=\"showArticle('+index+')\">查看</a>'+' ';\r\n");
      out.write("\t\tif(row.status == 1){\r\n");
      out.write("\t\t\tarticleOper +='<a href=\"#\" class=\"articleBtn\" onclick=\"toArticleUpdate('+index+')\">修改</a>'+' ';\r\n");
      out.write("\t\t\tarticleOper +='<a href=\"#\" class=\"articleBtn\" onclick=\"deleteArticle('+index+')\">删除</a>'+' ';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(row.status == 0){\r\n");
      out.write("\t\t\tarticleOper +='<a href=\"#\" class=\"articleBtn\" onclick=\"toArticleUpdate('+index+')\">修改</a>'+' ';\r\n");
      out.write("\t\t\tarticleOper +='<a href=\"#\" class=\"articleBtn\" onclick=\"refuseAtricle('+index+')\">拒绝</a>'+' ';\r\n");
      out.write("\t\t\tarticleOper +='<a href=\"#\" class=\"articleBtn\" onclick=\"recoverAtricle('+index+')\">审核</a>'+' ';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(row.status == 2){\r\n");
      out.write("\t\t\tarticleOper +='<a href=\"#\" class=\"articleBtn\" onclick=\"toArticleUpdate('+index+')\">修改</a>'+' ';\r\n");
      out.write("\t\t\tarticleOper +='<a href=\"#\" class=\"articleBtn\" onclick=\"recoverAtricle('+index+')\">恢复</a>'+' ';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(row.isrecommend == 0 && row.status == 1){\r\n");
      out.write("\t\t\tarticleOper +='<a href=\"#\" class=\"articleBtn\" onclick=\"isrecommendArticle('+index+')\">推荐</a>'+' ';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn articleOper;\r\n");
      out.write("\t} \t\r\n");
      out.write("\t\r\n");
      out.write("\t//跳转文章修改页面\r\n");
      out.write(" \tfunction toArticleUpdate(index){\r\n");
      out.write("\t\t$('#articleList').datagrid('selectRow',index);// 关键在这里 \r\n");
      out.write("\t    var row = $('#articleList').datagrid('getSelected'); \r\n");
      out.write("\t\tvar mainTab = parent.$('#main-center');\r\n");
      out.write("\t\tvar detailTab = {\r\n");
      out.write("\t\t\t\ttitle : \"修改文章\",\r\n");
      out.write("\t\t\t\tcontent:\"<iframe width='100%' height='100%' frameborder='0' src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/article/toArticleUpdate.do?artiId=\"+row.artiId+\"' ></iframe>\",\r\n");
      out.write("\t\t\t\tclosable : true\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tvar tab = mainTab.tabs(\"getSelected\");\r\n");
      out.write("\t\tvar index = mainTab.tabs('getTabIndex',tab);\r\n");
      out.write("\t\t/* if(index != 0){\r\n");
      out.write("\t\t\tmainTab.tabs('close',index);\r\n");
      out.write("\t\t} */\r\n");
      out.write("\t\tmainTab.tabs(\"add\",detailTab);\r\n");
      out.write("\t} \r\n");
      out.write("\t\r\n");
      out.write("\t//跳转文章显示页面\r\n");
      out.write(" \tfunction showArticle(index){\r\n");
      out.write("\t\t$('#articleList').datagrid('selectRow',index);// 关键在这里 \r\n");
      out.write("\t    var row = $('#articleList').datagrid('getSelected'); \r\n");
      out.write("\t\tvar mainTab = parent.$('#main-center');\r\n");
      out.write("\t\tvar detailTab = {\r\n");
      out.write("\t\t\t\ttitle : \"查看文章\",\r\n");
      out.write("\t\t\t\tcontent:\"<iframe width='100%' height='100%' frameborder='0' src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/article/showArticle.do?artiId=\"+row.artiId+\"' ></iframe>\",\r\n");
      out.write("\t\t\t\tclosable : true\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tvar tab = mainTab.tabs(\"getSelected\");\r\n");
      out.write("\t\tvar index = mainTab.tabs('getTabIndex',tab);\r\n");
      out.write("\t\t/* if(index != 0){\r\n");
      out.write("\t\t\tmainTab.tabs('close',index);\r\n");
      out.write("\t\t} */\r\n");
      out.write("\t\tmainTab.tabs(\"add\",detailTab);\r\n");
      out.write("\t} \r\n");
      out.write("\t\r\n");
      out.write("\t//修改显示状态信息\r\n");
      out.write("\tfunction formatStatus(value,row,index){\r\n");
      out.write("\t\tif(row.status==\"0\"){\r\n");
      out.write("\t\t\treturn '审核中';\r\n");
      out.write("\t\t}else if(row.status==\"1\"){\r\n");
      out.write("\t\t\treturn '已审核';\r\n");
      out.write("\t\t}else if(row.status==\"2\"){\r\n");
      out.write("\t\t\treturn '已拒绝';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//修改显示是否头条信息\r\n");
      out.write("\tfunction formatIsHead(value,row,index){\r\n");
      out.write("\t\tif(row.ishead==\"0\"){\r\n");
      out.write("\t\t\treturn '否';\r\n");
      out.write("\t\t}else if(row.ishead==\"1\"){\r\n");
      out.write("\t\t\treturn '是';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t//跳转文章添加页面\r\n");
      out.write("\tfunction addArticleBtn(){  \r\n");
      out.write("\t\tvar mainTab = parent.$('#main-center');\r\n");
      out.write("\t\tvar detailTab = {\r\n");
      out.write("\t\t\t\ttitle : \"添加文章\",\r\n");
      out.write("\t\t\t\tcontent:\"<iframe width='100%' height='100%' frameborder='0' src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/article/toArticleAdd.do' ></iframe>\",\r\n");
      out.write("\t\t\t\tclosable : true\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tvar tab = mainTab.tabs(\"getSelected\");\r\n");
      out.write("\t\tvar index = mainTab.tabs('getTabIndex',tab);\r\n");
      out.write("\t\t/* if(index != 0){\r\n");
      out.write("\t\t\tmainTab.tabs('close',index);\r\n");
      out.write("\t\t} */\r\n");
      out.write("\t\tmainTab.tabs(\"add\",detailTab);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction deleteArticle(index) {\r\n");
      out.write("\t\t$('#articleList').datagrid('selectRow',index);// 关键在这里 \r\n");
      out.write("\t    var row = $('#articleList').datagrid('getSelected'); \r\n");
      out.write("        $.messager.confirm('操作提示', '确定要删除吗?', function(r){\r\n");
      out.write("        \tif(r){\r\n");
      out.write("\t            $.ajax({\r\n");
      out.write("\t            \turl: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/article/deleteArticle.do?artiId=\"+row.artiId,\r\n");
      out.write("\t                type: 'POST',\r\n");
      out.write("\t               success:function(result){\r\n");
      out.write("\t\t\t\t\t\tif(result.success){\r\n");
      out.write("\t\t\t\t\t\t\t$.messager.alert(\"提示信息\",result.msg);\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#articleList\").datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t$.messager.alert(\"提示信息\",result.errorMsg);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t            });\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write(" \t}\r\n");
      out.write(" \t\r\n");
      out.write(" \tfunction isrecommendArticle(index) {\r\n");
      out.write(" \t\t$('#articleList').datagrid('selectRow',index);// 关键在这里 \r\n");
      out.write("\t    var row = $('#articleList').datagrid('getSelected'); \r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t       \turl: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/article/isrecommendArticle.do?artiId=\"+row.artiId,\r\n");
      out.write("\t        type: 'POST',\r\n");
      out.write("\t        success:function(result){\r\n");
      out.write("\t\t\t\tif(result.success){\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"提示信息\",result.msg);\r\n");
      out.write("\t\t\t\t\t$(\"#articleList\").datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"提示信息\",result.errorMsg);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("       });\r\n");
      out.write(" \t}\r\n");
      out.write(" \t\r\n");
      out.write(" \tfunction recoverAtricle(index) {\r\n");
      out.write(" \t\t$('#articleList').datagrid('selectRow',index);// 关键在这里 \r\n");
      out.write("\t    var row = $('#articleList').datagrid('getSelected'); \r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t       \turl: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/article/recoverAtricle.do?artiId=\"+row.artiId,\r\n");
      out.write("\t        type: 'POST',\r\n");
      out.write("\t        success:function(result){\r\n");
      out.write("\t\t\t\tif(result.success){\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"提示信息\",result.msg);\r\n");
      out.write("\t\t\t\t\t$(\"#articleList\").datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"提示信息\",result.errorMsg);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("       });\r\n");
      out.write(" \t}\r\n");
      out.write(" \t\r\n");
      out.write(" \tfunction refuseAtricle(index) {\r\n");
      out.write(" \t\t$('#articleList').datagrid('selectRow',index);// 关键在这里 \r\n");
      out.write("\t    var row = $('#articleList').datagrid('getSelected'); \r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t       \turl: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/article/refuseAtricle.do?artiId=\"+row.artiId,\r\n");
      out.write("\t        type: 'POST',\r\n");
      out.write("\t        success:function(result){\r\n");
      out.write("\t\t\t\tif(result.success){\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"提示信息\",result.msg);\r\n");
      out.write("\t\t\t\t\t$(\"#articleList\").datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$.messager.alert(\"提示信息\",result.errorMsg);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("       });\r\n");
      out.write(" \t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/jsp/system/article/sysArticleList.jsp(40,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/system/article/sysArticleList.jsp(40,5) '${sysProgram}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${sysProgram}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/jsp/system/article/sysArticleList.jsp(40,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("vt");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<option value='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vt.proId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('\'');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vt.proName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
