/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2018-04-19 07:47:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.system.sys.role;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;

public final class sysRoleList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/jsp/system/sys/role/../../../common/include/util.jsp", Long.valueOf(1523153962925L));
    _jspx_dependants.put("/WEB-INF/jsp/common/include/Taglibs.jsp", Long.valueOf(1523153962924L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    response.setHeader("Content-Type","text/html; charset=utf-8");
    request.setCharacterEncoding("utf-8");
    pageContext.setAttribute("pageEncoding","utf-8");
    
	String apppath = request.getContextPath();
	request.setAttribute("apppath", apppath);
	
	Date d = new Date();
	String tabid = "tabid"+d.getTime();
	request.setAttribute("tabid", tabid);

      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyUI/validatebox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apppath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/common/common.js\"></script>");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".onediv{width:350px; height:300px;float:left;margin:0 0 0 5px;  }\r\n");
      out.write(".twodiv{width:200px; height:300px;float:left;margin:0 0 0 5px;  }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<table id=\"roleList\" title=\"角色列表\" class=\"easyui-datagrid\" style=\"width:99.9%;height:99%;\"\r\n");
      out.write("\tdata-options=\"singleSelect:true,\r\n");
      out.write("\t    fitColumns:true, url: '../role/roleList.do',\r\n");
      out.write("\t    method:'post',rownumbers:true, \r\n");
      out.write("\t    pagination:true,toolbar:'#roleTools'\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t    <tr>\r\n");
      out.write("\t\t\t<th data-options=\"field:'roleKy'\" width=\"5%\">角色主键</th>\r\n");
      out.write("\t        <th data-options=\"field:'roleCode'\" width=\"10%\">角色编号</th>\r\n");
      out.write("\t        <th data-options=\"field:'roleName'\" width=\"15%\">角色名称</th>\r\n");
      out.write("\t        <th data-options=\"field:'roleRemarks'\" width=\"40%\">角色备注</th>\r\n");
      out.write("\t        <th data-options=\"field:'status'\" width=\"10%\" formatter=\"formatStatus\">状态</th>\r\n");
      out.write("\t\t\t<th data-options=\"field:'_operate',width:80,align:'center',formatter:formatOper\" width=\"18%\">基本操作</th>\r\n");
      out.write("\t    </tr>\r\n");
      out.write("\t    </thead>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div id=\"roleTools\" style=\"padding:5px;height:750\">\r\n");
      out.write("\t  \t<form id=\"roleForm\">\r\n");
      out.write("\t    \t角色名称：<input class=\"easyui-textbox\" id=\"searchRoleName\" name=\"roleName\" size=\"15\" style=\"width:100px\"/>\r\n");
      out.write("\t  \t\t状态： <select  id=\"searchRoleStatus\" name=\"status\" style=\"width:100px;\" class=\"easyui-combobox\">\r\n");
      out.write("\t\t\t\t \t<option value=''>全部</option>\r\n");
      out.write("\t\t\t\t\t<option value='1'>正常</option>\r\n");
      out.write("\t\t\t\t\t<option value='0'>禁用</option>\r\n");
      out.write("\t           </select>\r\n");
      out.write("\t    \t<a id=\"searchRoleBtn\" href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-search\">查询</a>\r\n");
      out.write("\t    \t<a id=\"resetRoleBtn\" href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-reload\">重置</a>\r\n");
      out.write("\t    \t<a href=\"#\" class=\"easyui-linkbutton\" iconCls=\"icon-add\" onclick=\"addRoleWindow()\">添加角色</a>\r\n");
      out.write("\t    </form>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"addRoleWindow\" class=\"easyui-window\" title=\"角色添加\" \r\n");
      out.write("\t\tdata-options=\"iconCls:'icon-add',closed:true,minimizable:false,resizable:false,maximizable:false\" style=\"width:700px;height:400px;padding:10px;\">\r\n");
      out.write("\t\t<form id=\"addRoleForm\">\r\n");
      out.write("\t\t<div class=\"onediv\">\r\n");
      out.write("\t    \t<table cellpadding=\"5\">\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td>角色名称:</td>\r\n");
      out.write("\t    \t\t\t<td><input id=\"roleName\" class=\"easyui-textbox\" type=\"text\" name=\"roleName\" data-options=\"required:true\"></input></td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td>角色编码:</td>\r\n");
      out.write("\t    \t\t\t<td><input id=\"roleCode\" class=\"easyui-textbox\" type=\"text\" name=\"roleCode\" data-options=\"required:true\"></input></td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td>角色描述:</td>\r\n");
      out.write("\t    \t\t\t<td><input class=\"easyui-textbox\" type=\"text\" name=\"roleRemarks\" data-options=\"required:true\" ></input></td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td>状态:</td>\r\n");
      out.write("\t    \t\t\t<td>\r\n");
      out.write("\t    \t\t\t\t<select name=\"status\" class=\"easyui-combobox\">\r\n");
      out.write("\t    \t\t\t\t\t<option value=\"1\">可用</option>\r\n");
      out.write("\t    \t\t\t\t\t<option value=\"0\">禁用</option>\r\n");
      out.write("\t    \t\t\t\t</select>\r\n");
      out.write("\t    \t\t\t</td>\r\n");
      out.write("\t    \t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t<div style=\"text-align:center;padding:5px\">\r\n");
      out.write("\t    \t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"checkRole()\">添加</a>\r\n");
      out.write("\t    \t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"clearRole()\">清空</a>\r\n");
      out.write("    \t</div>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t<div class=\"twodiv\">\r\n");
      out.write("\t\t<ul id=\"roletree\" class=\"easyui-tree\" data-options=\"url:'../role/menuTree.do',method:'get',animate:true,checkbox:true\"></ul>\r\n");
      out.write("    \t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"updateRole\" class=\"easyui-window\"\r\n");
      out.write("\t\tdata-options=\"iconCls:'icon-edit',closed:true,modal:true,minimizable:false,resizable:false,maximizable:false\" style=\"width:700px;height:450px;padding:10px;\">\r\n");
      out.write("\t</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("// \t$(function () {\r\n");
      out.write("// \t    $(\"#roletree\").tree({\r\n");
      out.write("// \t    \tcache:false,  \r\n");
      out.write("// \t    \tcascadeCheck: false,\r\n");
      out.write("// \t        onCheck: function (node, checked) {\r\n");
      out.write("// \t            if (checked) {\r\n");
      out.write("// \t                var parentNode = $(\"#roletree\").tree('getParent', node.target);\r\n");
      out.write("// \t                if (parentNode != null) {\r\n");
      out.write("// \t                    $(\"#roletree\").tree('check', parentNode.target);\r\n");
      out.write("// \t                }\r\n");
      out.write("// \t            } else {\r\n");
      out.write("//                      var childNode = $(\"#roletree\").tree('getChildren', node.target);\r\n");
      out.write("//                      if (childNode.length > 0) {\r\n");
      out.write("//                          for (var i = 0; i < childNode.length; i++) {\r\n");
      out.write("//                              $(\"#roletree\").tree('uncheck', childNode[i].target);\r\n");
      out.write("//                          }\r\n");
      out.write("//                      }\r\n");
      out.write("//                  }\r\n");
      out.write("// \t        }\r\n");
      out.write("// \t    });\r\n");
      out.write("// \t});\r\n");
      out.write("\t//重置按钮\r\n");
      out.write("\t$('#resetRoleBtn').click(function(){\r\n");
      out.write("\t\t$(\"#roleForm\").form(\"reset\");\r\n");
      out.write("\t\t$(\"#roleList\").datagrid(\"load\", {});\r\n");
      out.write("\t});\r\n");
      out.write("\t//查询按钮\r\n");
      out.write("\t$('#searchRoleBtn').click(function(){\r\n");
      out.write(" \t\t$('#roleList').datagrid({\r\n");
      out.write("\t\t\tqueryParams: {\r\n");
      out.write("\t\t\t\troleName: $('#searchRoleName').val(),\r\n");
      out.write("\t\t\t\tstatus: $('#searchRoleStatus').combobox(\"getValue\"),\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}); \r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction addRoleWindow(){ \r\n");
      out.write("\t\t$(\"#addRoleForm\").form(\"reset\");\r\n");
      out.write("\t\t$(\"#addRoleWindow\").window(\"open\");\r\n");
      out.write("\t \t$(\"#roletree\").tree('collapseAll');\r\n");
      out.write("\t }\r\n");
      out.write("\t//添加按钮\r\n");
      out.write(" \tfunction checkRole(){\r\n");
      out.write(" \t\tvar validate = $(\"#addRoleWindow\").form(\"validate\");\r\n");
      out.write("\t\tif(!validate){\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar roleName=$(\"#roleName\").val();\r\n");
      out.write("\t \tvar roleCode=$(\"#roleCode\").val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"../role/isExistNameOrCode.do\",\r\n");
      out.write("\t\t\tdata:\"roleName=\"+roleName+\"&roleCode=\"+ roleCode,\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tvar msg = data.message;\r\n");
      out.write("\t\t\t\tif(msg == \"ok\"){\r\n");
      out.write("\t\t\t\t\taddRole();\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tif(msg ==\"nameerror\"){\r\n");
      out.write("\t\t\t\t\t\t$.messager.alert(\"操作提示\", \"角色名存在！\");\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$.messager.alert(\"操作提示\", \"角色编码存在!\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror:  function (event, XMLHttpRequest, ajaxOptions, thrownError) {\r\n");
      out.write("\t\t\t\t$.messager.alert(\"操作提示\", \"系统异常，请联系管理员。\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t function addRole(){ \r\n");
      out.write("\t\t var selectedRightsList=\"\";\t\t\r\n");
      out.write("\t\t var node = $(\"#roletree\").tree('getChecked');\r\n");
      out.write("\t\t for(var i=0;i<node.length;i++)  \r\n");
      out.write("\t     {  \r\n");
      out.write("\t     \tselectedRightsList += \"&selectedRights=\" + node[i].id;\r\n");
      out.write("\t     }\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t\tvar data = $(\"#addRoleForm\").serialize() + selectedRightsList;\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"../role/tosysRoleAdd.do\",\r\n");
      out.write("\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\tdata : data,\r\n");
      out.write("\t\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\t\tsuccess: function(d){\r\n");
      out.write("\t\t\t\tvar msg = d.message;\r\n");
      out.write("\t\t\t\t\tif(msg == \"ok\"){\r\n");
      out.write("\t\t\t\t\t\t$.messager.alert(\"操作提示\", \"添加成功！\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#addRoleWindow\").window(\"close\");\r\n");
      out.write("\t\t\t\t\t\t$('#roleList').datagrid('reload');\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$.messager.alert(\"操作提示\", \"添加失败，请重试！\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror:function(args){\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t} \r\n");
      out.write("\t\r\n");
      out.write("\t//清空按钮\r\n");
      out.write("\tfunction clearRole(){\r\n");
      out.write("\t\t$(\"#addRoleForm\").form(\"reset\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//添加基本操作链接\r\n");
      out.write("\tfunction formatOper(val,row,index){  \r\n");
      out.write("    \treturn '<a href=\"#\" onclick=\"updateRoleWindow('+index+')\">修改</a>';  \r\n");
      out.write("\t} \r\n");
      out.write("\t\r\n");
      out.write("\t//更改状态\r\n");
      out.write("\tfunction updateStatus(index){  \r\n");
      out.write("\t\t$('#roleList').datagrid('selectRow',index);// 关键在这里 \r\n");
      out.write("\t    var row = $('#roleList').datagrid('getSelected'); \r\n");
      out.write("\t\t$.messager.confirm('操作提示', '你确定更改状态吗？', function(r){\r\n");
      out.write("\t\t\tif(r){\r\n");
      out.write("\t\t\t\tvar url = \"../role/updateRoleStatus.do?roleKy=\"+row.roleKy+\"&status=\"+row.status;\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl: url,\r\n");
      out.write("\t\t\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\t\t\tsuccess:function(){\r\n");
      out.write("\t\t\t\t\t\t$('#roleList').datagrid('reload');\r\n");
      out.write("\t\t\t\t\t\t$.messager.alert(\"操作提示\", \"操作成功\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t  \t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t} \r\n");
      out.write("\t\r\n");
      out.write("\t//添加状态链接\r\n");
      out.write("\tfunction formatStatus(value,row,index){\r\n");
      out.write("\t\tif(row.status==\"1\"){\r\n");
      out.write("\t\t\treturn '<a href=\"#\" onclick=\"updateStatus('+index+')\">可用</a>';\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\treturn '<a href=\"#\" onclick=\"updateStatus('+index+')\">禁用</a>';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//跳转修改也页面\r\n");
      out.write("\tfunction updateRoleWindow(index){  \r\n");
      out.write("\t\t$('#roleList').datagrid('selectRow',index);// 关键在这里 \r\n");
      out.write("\t    var row = $('#roleList').datagrid('getSelected'); \r\n");
      out.write("\t\t$(\"#updateRole\").window({\r\n");
      out.write("\t\t\ttitle:\"角色修改\",\r\n");
      out.write("\t\t\thref:\"../role/toUpdateRole.do?roleKy=\"+row.roleKy\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#updateRole\").window(\"open\");\r\n");
      out.write("\t} \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
