/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2018-05-30 08:11:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class ztth_005fwincall_005fkefu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>toolbar</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link href=\"js/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" media=\"screen\" />\r\n");
      out.write("    <link href=\"js/bootstrap/css/font-awesome.min.css\" rel=\"stylesheet\" media=\"screen\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script src=\"js/bootstrap/js/jquery.js\" ></script>\r\n");
      out.write("<script src=\"js/bootstrap/js/config.js\" ></script>\r\n");
      out.write("<script src=\"js/bootstrap/js/jquery.wincall.js\" ></script>\r\n");
      out.write("<script src=\"js/bootstrap/js/app.js\" ></script>\r\n");
      out.write("<script src=\"js/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("<object  width=\"0\" height=\"0\" classid=\"clsid:d27cdb6e-ae6d-11cf-96b8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0\" id=\"wincall\" align=\"middle\">\r\n");
      out.write("    <param name=\"allowScriptAccess\" value =\"always\" />\r\n");
      out.write("    <param name=\"allowFullScreen\" value=\"false\" />\r\n");
      out.write("    <param name=\"movie\" value=\"wincall400.swf\" />\r\n");
      out.write("    <param name=\"quality\" value=\"high\" />\r\n");
      out.write("    <param name=\"bgcolor\" value=\"#ffffff\" />\r\n");
      out.write("    <embed src=\"wincall400sss.swf\" width=\"0\" height=\"0\" id=\"wincall_emded\"  quality=\"high\" name=\"wincall\" align=\"middle\" allowScriptAccess=\"sameDomain\" allowFullScreen=\"false\" type=\"application/x-shockwave-flash\" pluginspage=\"http://www.macromedia.com/go/getflashplayer\" />\r\n");
      out.write("</object>\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"row-fluid\">\r\n");
      out.write("        <div class=\"pull-left\" id='toolbar'>\r\n");
      out.write("            <!-- #section:elements.button.app -->\r\n");
      out.write("            <button class=\"btn btn-info \" id=\"ztth_login\">\r\n");
      out.write("                <i class=\"fa fa-circle-o-notch  fa-1x\" ></i><br/>\r\n");
      out.write("                <span id='ztth_login_value'>签入</span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"btn btn-default \" id=\"ztth_unbusy\" disabled=\"disabled\">\r\n");
      out.write("                <i class=\"fa fa-slack fa-1x\"></i><br/>\r\n");
      out.write("                置闲\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"btn btn-default\" id=\"ztth_busy\" disabled=\"disabled\">\r\n");
      out.write("                <i class=\"fa fa-jsfiddle fa-1x\"></i><br/>\r\n");
      out.write("                置忙\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"btn btn-default\" id=\"ztth_callinner\" disabled=\"disabled\">\r\n");
      out.write("                <i class=\"fa fa-bomb fa-1x\"></i><br/>\r\n");
      out.write("                内呼\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"btn btn-default\" id=\"ztth_callouter\" disabled=\"disabled\" >\r\n");
      out.write("                <i class=\"fa fa-cube fa-1x\"></i><br/>\r\n");
      out.write("                外呼\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"btn btn-default\" id=\"ztth_hangup\" disabled=\"disabled\">\r\n");
      out.write("                <i class=\"fa fa-volume-off fa-1x\"></i><br/>\r\n");
      out.write("                挂断\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"btn btn-default\" id=\"ztth_hold\" disabled=\"disabled\">\r\n");
      out.write("                <i class=\"fa fa-pause fa-1x\"></i><br/>\r\n");
      out.write("                <span id='ztth_hold_value'>保持</span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"btn btn-default\" id=\"ztth_evaluation\" disabled=\"disabled\">\r\n");
      out.write("                <i class=\"fa fa-play fa-1x\"></i><br/>\r\n");
      out.write("                满意度\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"btn btn-default\" id=\"ztth_consultinner\" disabled=\"disabled\">\r\n");
      out.write("                <i class=\"fa fa-user fa-1x\"></i><br/>\r\n");
      out.write("                咨询坐席\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"btn btn-default\" id=\"ztth_consultouter\" disabled=\"disabled\">\r\n");
      out.write("                <i class=\"fa fa-phone fa-1x\"></i><br/>\r\n");
      out.write("                咨询外线\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"btn btn-default\" id=\"ztth_consultback\" disabled=\"disabled\">\r\n");
      out.write("                <i class=\"fa fa-reply fa-1x\"></i><br/>\r\n");
      out.write("                咨询接回\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"btn btn-default\" id=\"ztth_transfer\" disabled=\"disabled\">\r\n");
      out.write("                <i class=\"fa fa-random fa-1x\"></i><br/>\r\n");
      out.write("                转接\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"btn btn-default\" id=\"ztth_threeway\" disabled=\"disabled\">\r\n");
      out.write("                <i class=\"fa fa-group fa-1x\"></i><br/>\r\n");
      out.write("                三方\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"btn btn-default\" id=\"ztth_threewayback\" disabled=\"disabled\">\r\n");
      out.write("                <i class=\"fa fa-undo fa-1x\"></i><br/>\r\n");
      out.write("                三方接回\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"btn btn-default\" id=\"ztth_chanspy\" disabled=\"disabled\">\r\n");
      out.write("                <i class=\"fa fa-headphones fa-1x\"></i><br/>\r\n");
      out.write("                监听\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"btn btn-default\" id=\"ztth_breakin\" disabled=\"disabled\">\r\n");
      out.write("                <i class=\"fa fa-arrow-down fa-1x\"></i><br/>\r\n");
      out.write("                强插\r\n");
      out.write("            </button>\r\n");
      out.write("\t\t\t<button class=\"btn btn-default\" id=\"ztth_intercept\" disabled=\"disabled\">\r\n");
      out.write("                <i class=\"fa fa-arrow-down fa-1x\"></i><br/>\r\n");
      out.write("                拦截\r\n");
      out.write("            </button>\r\n");
      out.write("            <!-- /section:elements.button.app -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"pull-right\">\r\n");
      out.write("            <span class=\"label\">坐席状态：</span><span class=\"label label-success\" id='ztth_seat_state' >未签入</span><br>\r\n");
      out.write("            <span class=\"label\">队列状态：</span><span class=\"label label-success\" id='ztth_queue_state'>未签入</span><br>\r\n");
      out.write("            <span><span id='ztth_phone_error' class=\"label label-important hide\">电话注册失败</span></span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"ztth_myModal\" class=\"modal hide fade\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">×</button>\r\n");
      out.write("            <h3 id=\"ztth_myModalLabel\">Modal header</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\" id='ztth_modal_content'>\r\n");
      out.write("            <p></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("            <button class=\"btn\" data-dismiss=\"modal\" aria-hidden=\"true\" id='ztth_btn_hidden'>关闭</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--内呼框--->\r\n");
      out.write("<div id=\"callinner_content\" style=\"display:none\">\r\n");
      out.write(" <form class=\"form-horizontal\">\r\n");
      out.write("    <div class=\"control-group\">\r\n");
      out.write("\t\t<label class=\"control-label\" for=\"agent_num\" id=\"ztth_agent_num\">坐席工号:</label>\r\n");
      out.write("\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"ztth_pc_user_num\" placeholder=\"\" >\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"control-group\">\r\n");
      out.write("\t\t<label class=\"control-label\" for=\"num_list\" id=\"ztth_inner_number\">主叫号码:</label>\r\n");
      out.write("\t\t<div class=\"controls\" id=\"ztth_num_list\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("    <div class=\"control-group\">\r\n");
      out.write("\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn\" id='ztth_pc_callinner_btn' onclick=\"innerCall()\"> 呼叫</button>\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"ztth_inner_agent_flag\" value = \"\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("    <div>\r\n");
      out.write("        <table class=\"table table-bordered\" id='ztth_innerTable'>\r\n");
      out.write("\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write(" </form>\r\n");
      out.write("</div>\r\n");
      out.write("<!--外呼框--->\r\n");
      out.write("<div id=\"callout_content\" style=\"display:none\">\r\n");
      out.write("    <form class=\"form-horizontal\">\r\n");
      out.write("        <div class=\"control-group\">\r\n");
      out.write("            <label class=\"control-label\" for=\"callouter_num\" id=\"ztth_number_label\">外呼号码:</label>\r\n");
      out.write("            <div class=\"controls\">\r\n");
      out.write("                <input type=\"text\" id=\"ztth_callouter_num\" placeholder=\"\" />\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t\t<!--\r\n");
      out.write("        <div class=\"control-group\" id=\"que_list_label\">\r\n");
      out.write("            <label class=\"control-label\" for=\"out_que_list\" >选择技能组:</label>\r\n");
      out.write("            <div class=\"controls\" id='out_que_list'>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>-->\r\n");
      out.write("        <div class=\"control-group\">\r\n");
      out.write("            <label class=\"control-label\" for=\"out_que_num\">选择主叫号码:</label>\r\n");
      out.write("            <div class=\"controls\" id='ztth_out_que_num'>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"control-group\">\r\n");
      out.write("            <div class=\"controls\">\r\n");
      out.write("                <button type=\"button\" class=\"btn ztth_callouter_btn\" id='ztth_callouter_btn' onclick=\"clickOutNumKefu()\"> 呼叫</button>\r\n");
      out.write("                <input type=\"hidden\" value=\"1\" id=\"ztth_out_inner_flag\" />\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"ztth_chanspy_content\" style=\"display:none\">\r\n");
      out.write("    <div>\r\n");
      out.write("        <table class=\"table table-bordered\" id='ztth_chanspyTable'>\r\n");
      out.write("\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--来电弹框--->\r\n");
      out.write("<div id=\"incoming_dialog\" style=\"display:none\">\r\n");
      out.write("    <div id=\"callin_number\" style=\"color:red;font-size:25px;\"></div>\r\n");
      out.write("    <div id=\"calling_loc\"  style=\"color:red;font-size:25px;\"></div>\r\n");
      out.write("    <button class=\"btn\" data-dismiss=\"modal\" aria-hidden=\"true\" id='ztth_btn_jieting' onclick=\"ztthAnswer()\">接听</button>\r\n");
      out.write("    <button class=\"btn\" data-dismiss=\"modal\" aria-hidden=\"true\" id='ztth_btn_jujie' onclick=\"ztthReject()\">拒接</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
